# Generated by Django 4.1.5 on 2023-03-18 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'mes',
                'verbose_name_plural': 'meses',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'estado',
                'verbose_name_plural': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago:')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificación:')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='comprobantes', verbose_name='Comprobante')),
                ('email_client', models.EmailField(max_length=254, unique=True)),
                ('month', models.ManyToManyField(to='payments.month', verbose_name='Mes de pago')),
                ('name_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre del cliente')),
                ('state', models.ManyToManyField(to='payments.state', verbose_name='Estado')),
            ],
        ),
    ]
