# Generated by Django 4.1.5 on 2023-03-18 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='email_client',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico del cliente'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='state',
        ),
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='payments.month', verbose_name='Mes de pago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='state',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='payments.state', verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
