# Generated by Django 4.1.5 on 2023-04-19 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='email_client',
            field=models.EmailField(max_length=254, null=True, verbose_name='Correo electrónico del cliente'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre del cliente'),
        ),
    ]
