# Generated by Django 4.1.5 on 2023-03-19 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_email_client_remove_payment_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'pago', 'verbose_name_plural': 'pagos'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'estado', 'verbose_name_plural': 'estados'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='email_client',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico del cliente'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.month', verbose_name='Mes de pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.state', verbose_name='Estado'),
        ),
    ]
